// Usage: npx tsx scripts/categorize-migration.ts <NNNN_name>
// Writes data/migrations/<NNNN_name>.sql replacing every category and every thread↔category link with the
// reviewed categorization in data/categorization/ (taxonomy.json + assignments.json). The generated SQL is
// versioned and applied with `npm run db:migrate`, so the database is never edited by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Taxonomy {
  categories: { slug: string; name: string; description: string; intro: string; criteria: string; position: number }[];
}
interface Assignment {
  id: string;
  primary: string;
  secondary: string[];
}

const name = process.argv[2];
if (!name || !/^\d{4}_[a-z0-9_]+$/.test(name)) {
  console.error('Usage: npx tsx scripts/categorize-migration.ts <NNNN_name>');
  process.exit(1);
}

const dir = join(process.cwd(), 'data', 'categorization');
const taxonomy = JSON.parse(readFileSync(join(dir, 'taxonomy.json'), 'utf8')) as Taxonomy;
const assignments = JSON.parse(readFileSync(join(dir, 'assignments.json'), 'utf8')) as Assignment[];

const slugs = new Set(taxonomy.categories.map((c) => c.slug));
for (const a of assignments) {
  for (const slug of [a.primary, ...a.secondary]) if (!slugs.has(slug)) throw new Error(`${a.id}: unknown category ${slug}`);
}

const sql = (value: string | number) => (typeof value === 'number' ? String(value) : `'${value.replaceAll("'", "''")}'`);

const lines = [
  `-- Generated by scripts/categorize-migration.ts from data/categorization/ (taxonomy.json + assignments.json).`,
  `-- Replaces the legacy categories with the reviewed set and recategorizes every turra: position 0 = primary.`,
  'DELETE FROM thread_categories;',
  'DELETE FROM categories;',
  '',
  ...[...taxonomy.categories]
    .sort((a, b) => a.position - b.position)
    .map(
      (c) =>
        // Guarded so a fresh database (tests) stays empty: this is data for the archive, not schema
        `INSERT INTO categories (slug, name, description, intro, criteria, position) SELECT ${[c.slug, c.name, c.description, c.intro, c.criteria, c.position].map(sql).join(', ')} WHERE EXISTS (SELECT 1 FROM threads);`,
    ),
  '',
  ...assignments.flatMap((a) =>
    [a.primary, ...a.secondary].map(
      (slug, position) =>
        `INSERT INTO thread_categories (thread_id, category_slug, position) SELECT ${sql(a.id)}, ${sql(slug)}, ${position} WHERE EXISTS (SELECT 1 FROM threads WHERE id = ${sql(a.id)});`,
    ),
  ),
  '',
];

const out = join(process.cwd(), 'data', 'migrations', `${name}.sql`);
writeFileSync(out, lines.join('\n'));
console.log(`${taxonomy.categories.length} categories, ${assignments.length} turras → ${out}`);
