// Usage: npx tsx scripts/categorize-books.ts [NNNN_migration_name]
// Merges the two independent book classification passes (data/categorization/books-pass-a, books-pass-b):
// - same primary in both → accepted; secondary kept only when both passes gave it
// - different primary → must be decided in books-resolutions.json ({url: {primary, secondary, reason}})
// Writes books-assignments.json and books-disagreements.md. With a migration name, also writes
// data/migrations/<name>.sql setting every book's categories (primary first).
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Pass {
  url: string;
  primary: string;
  secondary: string[];
  reason: string;
  confidence: string;
}
interface Resolution {
  primary: string;
  secondary: string[];
  reason: string;
}

const dir = join(process.cwd(), 'data', 'categorization');
const names = new Set(
  (JSON.parse(readFileSync(join(dir, 'books-taxonomy.json'), 'utf8')) as { categories: { name: string }[] }).categories.map((c) => c.name),
);
const readPass = (name: string) =>
  new Map(
    readdirSync(join(dir, name))
      .filter((file) => file.endsWith('.json'))
      .flatMap((file) => JSON.parse(readFileSync(join(dir, name, file), 'utf8')) as Pass[])
      .map((p) => [p.url, p]),
  );
const a = readPass('books-pass-a');
const b = readPass('books-pass-b');
let resolutions: Record<string, Resolution> = {};
try {
  resolutions = JSON.parse(readFileSync(join(dir, 'books-resolutions.json'), 'utf8')) as Record<string, Resolution>;
} catch {
  // No resolutions yet
}

const urls = [...a.keys()];
if (urls.length !== b.size || urls.some((url) => !b.has(url))) throw new Error('books-pass-a and books-pass-b cover different books');

const assignments: { url: string; categories: string[] }[] = [];
const report: string[] = [];
const unresolved: string[] = [];
let agreed = 0;

for (const url of urls) {
  const pa = a.get(url)!;
  const pb = b.get(url)!;
  const resolution = resolutions[url];
  let categories: string[];
  if (resolution) {
    categories = [resolution.primary, ...resolution.secondary];
    report.push(
      `## ${url}\n- Pasada A: ${pa.primary} (${pa.secondary.join(', ') || '—'}): ${pa.reason}\n` +
        `- Pasada B: ${pb.primary} (${pb.secondary.join(', ') || '—'}): ${pb.reason}\n` +
        `- **Decisión: ${resolution.primary}** (${resolution.secondary.join(', ') || '—'}). ${resolution.reason}\n`,
    );
    if (pa.primary === pb.primary) agreed++;
  } else if (pa.primary === pb.primary) {
    agreed++;
    categories = [pa.primary, ...pa.secondary.filter((name) => pb.secondary.includes(name))];
  } else {
    unresolved.push(`${url}: A=${pa.primary} B=${pb.primary}`);
    continue;
  }
  for (const name of categories) if (!names.has(name)) throw new Error(`${url}: unknown category ${name}`);
  assignments.push({ url, categories });
}

const rate = ((agreed / urls.length) * 100).toFixed(1);
console.log(`${urls.length} books, primary agreed in ${agreed} (${rate} %), resolved ${Object.keys(resolutions).length}`);
if (unresolved.length > 0) {
  console.error(`Unresolved (${unresolved.length}):\n${unresolved.join('\n')}`);
  process.exit(1);
}

writeFileSync(join(dir, 'books-assignments.json'), `${JSON.stringify(assignments, null, 2)}\n`);
writeFileSync(
  join(dir, 'books-disagreements.md'),
  `# Desacuerdos entre las dos pasadas (libros)\n\nAcuerdo en la categoría principal: ${agreed} de ${urls.length} libros (${rate} %).\n\n${report.join('\n')}`,
);

const migration = process.argv[2];
if (migration) {
  if (!/^\d{4}_[a-z0-9_]+$/.test(migration)) throw new Error('Migration name must look like NNNN_name');
  const sql = (value: string) => `'${value.replaceAll("'", "''")}'`;
  const lines = [
    '-- Generated by scripts/categorize-books.ts from data/categorization/books-assignments.json:',
    '-- every book gets its reviewed categories (primary first).',
    ...assignments.map((x) => `UPDATE books SET categories_json = ${sql(JSON.stringify(x.categories))} WHERE url = ${sql(x.url)};`),
    '',
  ];
  writeFileSync(join(process.cwd(), 'data', 'migrations', `${migration}.sql`), lines.join('\n'));
  console.log(`→ data/migrations/${migration}.sql`);
}
