// Usage: npx tsx scripts/fix-metadata-extensions.ts NNNN_name
// Some images in public/metadata/ were saved without an extension, so they are served as
// application/octet-stream and search engines crawl them as documents. This renames each one with the
// extension of its real format, writes a migration that updates every path stored in the database, and
// records old → new in data/metadata-renames.json (next.config.ts redirects the old URLs with a 308).
import { existsSync, readdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const name = process.argv[2];
if (!name || !/^\d{4}_[a-z0-9_]+$/.test(name)) {
  console.error('Usage: npx tsx scripts/fix-metadata-extensions.ts NNNN_name');
  process.exit(1);
}

const dir = join(process.cwd(), 'public', 'metadata');
const renamesFile = join(process.cwd(), 'data', 'metadata-renames.json');
const renames = existsSync(renamesFile) ? (JSON.parse(readFileSync(renamesFile, 'utf8')) as Record<string, string>) : {};
const EXTENSION: Record<string, string> = { jpeg: 'jpg', png: 'png', webp: 'webp', gif: 'gif', avif: 'avif', svg: 'svg' };

const added: [string, string][] = [];
for (const file of readdirSync(dir).filter((f) => !f.includes('.'))) {
  const { format } = await sharp(join(dir, file)).metadata();
  const extension = format ? EXTENSION[format] : undefined;
  if (!extension) {
    console.warn(`Skipped ${file}: unknown format ${format}`);
    continue;
  }
  const target = `${file}.${extension}`;
  if (existsSync(join(dir, target))) {
    console.warn(`Skipped ${file}: ${target} already exists`);
    continue;
  }
  renameSync(join(dir, file), join(dir, target));
  added.push([`/metadata/${file}`, `/metadata/${target}`]);
}

const sql = (value: string) => `'${value.replaceAll("'", "''")}'`;
const lines = ['-- Generated by scripts/fix-metadata-extensions.ts: image paths now carry their real extension.'];
for (const [from, to] of added) {
  lines.push(
    `UPDATE media SET url = ${sql(to)} WHERE url = ${sql(from)};`,
    `UPDATE media SET poster_url = ${sql(to)} WHERE poster_url = ${sql(from)};`,
    `UPDATE links SET image_url = ${sql(to)} WHERE image_url = ${sql(from)};`,
    `UPDATE books SET image_url = ${sql(to)} WHERE image_url = ${sql(from)};`,
    // Inside the JSON of quoted tweets the path is followed by its closing quote, so a prefix never matches
    `UPDATE quotes SET media_json = REPLACE(media_json, ${sql(`"${from}"`)}, ${sql(`"${to}"`)}) WHERE media_json LIKE ${sql(`%"${from}"%`)};`,
  );
}
writeFileSync(join(process.cwd(), 'data', 'migrations', `${name}.sql`), `${lines.join('\n')}\n`);
writeFileSync(renamesFile, `${JSON.stringify({ ...renames, ...Object.fromEntries(added) }, null, 2)}\n`);
console.log(`${added.length} images renamed → data/migrations/${name}.sql`);
