// Usage: npx tsx scripts/glossary-migration.ts <NNNN_name>
// Writes data/migrations/<NNNN_name>.sql replacing the glossary with the reviewed entries of
// data/glossary/glossary.json, so the database is never edited by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Entry {
  slug: string;
  term: string;
  short: string;
  body: string;
  origin: string | null;
  group: string;
  aliases: string[];
  related: string[];
  sources: { threadId: string; tweetId: string | null }[];
  domains?: { name: string; text: string }[];
}

const name = process.argv[2];
if (!name || !/^\d{4}_[a-z0-9_]+$/.test(name)) {
  console.error('Usage: npx tsx scripts/glossary-migration.ts <NNNN_name>');
  process.exit(1);
}

const entries = JSON.parse(readFileSync(join(process.cwd(), 'data', 'glossary', 'glossary.json'), 'utf8')) as Entry[];
const sql = (value: string | null) => (value === null ? 'NULL' : `'${value.replaceAll("'", "''")}'`);

const lines = [
  '-- Generated by scripts/glossary-migration.ts from data/glossary/glossary.json.',
  'DELETE FROM glossary;',
  ...entries.map(
    (e) =>
      `INSERT INTO glossary (slug, term, short, body, origin, group_name, aliases_json, related_json, sources_json, domains_json) VALUES (${[
        e.slug,
        e.term,
        e.short,
        e.body,
        e.origin,
        e.group,
        JSON.stringify(e.aliases),
        JSON.stringify(e.related),
        JSON.stringify(e.sources.map(({ threadId, tweetId }) => ({ threadId, tweetId }))),
        e.domains ? JSON.stringify(e.domains) : null,
      ]
        .map(sql)
        .join(', ')});`,
  ),
  '',
];

const out = join(process.cwd(), 'data', 'migrations', `${name}.sql`);
writeFileSync(out, lines.join('\n'));
console.log(`${entries.length} terms → ${out}`);
